### ISSUE TITLE
'Usage from command line' feature

### ISSUE THREAD

**Issue by sugizo** [EchterAlsFake/xvideos_api#2]
**objective** 
nice to have 'Usage from command line' feature

**e.g. like phub**
```
# Download a single video
xvideos_api https://www.xvideos.com/view_video.php?viewkey=abcdef
# Download multiple videos from a text file
xvideos_api path/to/file.txt --quality best --downloader threaded --output video.mp4
```

best regards

**Comment by EchterAlsFake** [comment]
Yes I'll implement that later or tomorrow.  Oh and I will also fix the other issues you've reported in my other repos. 

Thanks for your ideas and testing :)

**Comment by EchterAlsFake** [comment]
Implemented, you can now just do:

xvideos_api -h

which will print the available options. It works exactly like phub :) 

(It's not on Pypi yet, so you need to install it from this repo)
